### ISSUE TITLE
Light themes seem to display incorrect font colors.

### ISSUE THREAD

**Issue by steven-smith-IT** [saberzero1/quartz-themes#27]
The two themes that I've tested so far are Catppuccin and tokyo night. The below screenshots were taken with cache disabled through dev tools in firefox.
It seems that the light theme is inheriting the font colors of the dark theme which makes it almost unreadable.

Catppuccin:
Dark:
![Screenshot From 2024-12-24 20-52-31](https://github.com/user-attachments/assets/930ade9b-c802-400a-842f-e013802294d3)
Light:
![Screenshot From 2024-12-24 20-52-52](https://github.com/user-attachments/assets/5c19b04d-8dc9-4cd2-bf03-7fc245a2c4f6)

Tokyo Night:
Dark:
![image](https://github.com/user-attachments/assets/6a6f430c-b836-493c-a66c-c81584337d3d)
Light:
![image](https://github.com/user-attachments/assets/79ddf0d3-b2ae-4190-aace-b43434e77cf4)

**Comment by steven-smith-IT** [comment]
I've been able to get a bit more context but I'm not very versed in CSS to explain why this is happening. It seems like the text color is specified as --lightgray. This doesn't seem to change between themes.
![Screenshot From 2024-12-27 15-01-21](https://github.com/user-attachments/assets/3c12c31f-1f7e-4f68-9dc2-e7ffebc697d3)

**Comment by saberzero1** [comment]
Fixed in https://github.com/saberzero1/quartz-themes/pull/28
